import Foundation

/// 表示用の文字列はすべて Localizable.strings 側に持つ。
/// ここでは構造（順序・時間・色）だけを定義する。
private func person(_ slug: String, era: String, blocks: [(String, Double, Int)]) -> Person {
    Person(
        name: L("person.\(slug).name"),
        era: era,
        bio: L("person.\(slug).bio"),
        timeBlocks: blocks.map { TimeBlock(name: L("activity.\($0.0)"), hours: $0.1, colorIndex: $0.2) }
    )
}

let samplePersons: [Person] = [
    person("darwin", era: "1809–1882", blocks: [
        ("sleep",            8,   0),
        ("morning_walk",     1,   2),
        ("research_writing", 3,   1),
        ("lunch_break",      1.5, 4),
        ("reading_letters",  2,   5),
        ("afternoon_walk",   1.5, 2),
        ("research_afternoon", 3, 1),
        ("dinner_family",    2,   3),
        ("reading_bedtime",  2,   6),
    ]),
    person("beethoven", era: "1770–1827", blocks: [
        ("sleep",               6, 0),
        ("breakfast_coffee",    1, 6),
        ("composing_morning",   5, 1),
        ("lunch_walk",          2, 2),
        ("composing_afternoon", 3, 1),
        ("dinner",              1, 3),
        ("reading_social",      3, 5),
        ("evening_walk",        1, 2),
        ("bedtime_prep",        2, 4),
    ]),
    person("kafka", era: "1883–1924", blocks: [
        ("sleep",              6,   0),
        ("breakfast_commute",  1,   6),
        ("work_insurance",     6,   3),
        ("lunch_family",       2,   5),
        ("nap",                1.5, 4),
        ("exercise",           1,   2),
        ("dinner",             1,   1),
        ("writing_night",      3.5, 7),
        ("reading",            2,   8),
    ]),
    person("franklin", era: "1706–1790", blocks: [
        ("sleep",               7, 0),
        ("morning_planning",    1, 6),
        ("breakfast_reading",   1, 5),
        ("work_morning",        4, 1),
        ("lunch_reading",       2, 2),
        ("work_afternoon",      4, 1),
        ("dinner_social",       2, 3),
        ("music_conversation",  2, 4),
        ("daily_review",        1, 7),
    ]),
    person("angelou", era: "1928–2014", blocks: [
        ("sleep",           7,   0),
        ("breakfast_prep",  1,   6),
        ("writing_hotel",   6,   1),
        ("lunch",           1,   5),
        ("reading_input",   2,   8),
        ("exercise",        1,   2),
        ("dinner",          1.5, 3),
        ("family_friends",  2,   4),
        ("reading_bedtime", 2.5, 7),
    ]),
    person("kant", era: "1724–1804", blocks: [
        ("sleep",              7, 0),
        ("wake_tea_thinking",  1, 6),
        ("writing_thinking",   3, 1),
        ("lecture",            4, 3),
        ("lunch_long",         2, 5),
        ("walk",               1, 2),
        ("reading",            4, 8),
        ("bedtime_snack",      2, 4),
    ]),
    person("churchill", era: "1874–1965", blocks: [
        ("sleep",           8,   0),
        ("writing_in_bed",  3,   1),
        ("breakfast_newspaper", 1, 6),
        ("work_morning",    2,   3),
        ("lunch_social",    1.5, 5),
        ("afternoon_nap",   1.5, 4),
        ("work_afternoon",  3,   1),
        ("dinner_society",  2,   9),
        ("work_late_night", 2,   7),
    ]),
    person("curie", era: "1867–1934", blocks: [
        ("sleep",               7,   0),
        ("breakfast_prep",      1,   6),
        ("research_morning",    5,   1),
        ("lunch_simple",        0.5, 3),
        ("research_afternoon",  5.5, 1),
        ("dinner_family",       2,   5),
        ("paper_writing",       2,   8),
        ("bedtime_prep",        1,   4),
    ]),
    person("tchaikovsky", era: "1840–1893", blocks: [
        ("sleep",               8,   0),
        ("wake_tea_reading",    2,   6),
        ("composing_morning",   3,   1),
        ("lunch",               1,   3),
        ("walk_required",       2,   2),
        ("composing_afternoon", 3,   1),
        ("dinner",              1.5, 5),
        ("reading_social",      2,   9),
        ("bedtime_prep",        1.5, 4),
    ]),
    person("davinci", era: "1452–1519", blocks: [
        ("sleep_polyphasic",     5.5, 0),
        ("painting_morning",     4,   7),
        ("walk_nature",          1.5, 2),
        ("lunch",                1,   3),
        ("anatomy_science",      3,   1),
        ("painting_afternoon",   4,   7),
        ("students_social",      2,   9),
        ("sketch_reading",       3,   8),
    ]),
]
